version: '3.8'
services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}
    command: npm run start:dev
    networks:
      - default
  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=${FRONTEND_PORT}
    command: npm run serve
    networks:
      - default
volumes:
  pgdata:
networks:
  default:
    driver: bridge